### ISSUE TITLE
Image source has error and out of date dep.

### ISSUE THREAD

**Issue by vim2meta** [LJNeon/banana-farm#2]
[This image](https://raw.githubusercontent.com/LJNeon/banana-farm/master/images/banana-farm.png) from your readme has an error and won't display. Also, your eris dependency is out of date.

**Comment by LJNeon** [comment]
Yeah this is extremely out of date, how long it took for me to even notice your issue proves it.

There should be a major update to Banana Farm around the start of December, I'll update this then.
